### PR TITLE
Handle GO15VENDOREXPERIMENT properly across Go versions

### LINKED ISSUE #147: codecgen: wrongly generated vendored import paths under Go 1.6
When building (and invoking) codecgen with Go 1.6 on a package with vendored dependencies it generates import paths like: `github.com/weaveworks/scope/vendor/github.com/ugorji/go/codec` instead of `github.com/ugorji/go/codec`.

It works when setting `GO15VENDOREXPERIMENT=1` but this is not required with Go 1.6 

See https://golang.org/doc/go1.6#go_command :

> Go 1.6 keeps the vendoring support, no longer considered experimental, and enables it by default. It can be disabled explicitly by setting the GO15VENDOREXPERIMENT environment variable to 0. Go 1.7 will remove support for the environment variable.

### PR DESCRIPTION
**Pull request by 2opremio**
Fixes #147

### CODE REVIEW

**Comment by ugorji** [comment]
I don't agree with this fix.

For one, it only works for releases. go version for development looks like:

```
go version devel +8a2d6e9 Mon Mar 14 14:53:29 2016 +0000 linux/amd64
```

This doesn't have a go1.N in there anywhere. This PR only works fine for releases. 

The proper solution is to use build tags. This way, the job of determining what code to use is the purview of the build tool, and not our code deciphering it. 

I have a change for that which I will submit soon.

**Comment by 2opremio** [comment]
Won't build tags lead to inconsistent results if gen.go is built with one
version of Go and codecgen (i.e go run) is invoked with a different Go
version?

**Comment by ugorji** [comment]
I took some time to think about this earlier.

codecgen is run by taking the .go input files and the GO SDK, and generates new go files. It is not a build tool - it is a runtime generation tool. The installed Go SDK that it uses determines how it handles vendored things, etc.

There's consequently no separate point where gen.go is built. That Go SDK will select appropriately based on its version.

**Comment by ugorji** [comment]
907292679fff3dbc38f9bb2361f47953ed7aea75 is the fix for #147

**Comment by 2opremio** [comment]
fair enough

**Pull request closed without merging**
