### PR TITLE
Generate encoders with canonical support

### PR DESCRIPTION
**Pull request by mxmauro**

### CODE REVIEW

**Comment by ugorji** [comment]
I'm not sure about this commit.

It should be sufficient to just change genStructCanonical = true. 
Can you try that and let me know if it works well?

Better yet, maybe we should make it a codecgen option.
For folks that don't care about Canonical, it bloats the generated code, which has detrimental effects.

@mxmauro lemme know your thoughts please.

**Comment by mxmauro** [comment]
If I remember correctly, the problem was `tisfi` was generated from `ti.sfi.source()` but later, the code generator calls `fn` twice, one for canonical and then for non-canonical. This causes the `j` index to be wrong. That's why I added the position.

**Comment by ugorji** [comment]
Got you.

If you don't mind, lemme try to rework this a bit. Make sure I'm not missing anywhere else that the source index should be used.

**Comment by mxmauro** [comment]
Of course. Go ahead. 😉

**Comment by ugorji** [comment]
Fixed at e8f277c38f5c0724e5a7be7dbe09d1a60f0e6010

**Comment by ugorji** [comment]
Fixed at e8f277c38f5c0724e5a7be7dbe09d1a60f0e6010

**Pull request closed without merging**
