### PR TITLE
Fixes to TypeInfos

### PR DESCRIPTION
**Pull request by dancannon**
I realise this is a bit of an open-ended PR but I discovered a couple of issues when testing the library and thought I would have a go at fixing them. I imagine you will have a couple of ideas on how to improve my attempts but I hope you appreciate my attempt :)

This is still a work in progress and I still need to figure out how to structure some tests, if you have any pointers that would be great.

Here is the file I am using to test my changes https://gist.github.com/dancannon/0c44f79d5189c4c35b3b

Changes: 
 - Support infinitely nested data structures

### CODE REVIEW

**Comment by dancannon** [comment]
I believe the issue where some fields are missing is due to the ordering of embedded fields. I have narrowed it down to this section of code: https://github.com/ugorji/go/blob/master/codec/helper.go#L904-L909.

Not yet sure how this can be fixed.

**Comment by ugorji** [comment]
I'm not sure what the pull request is supposed to fix, or what it is trying to do.

Can you file an issue first, add a reproducer, explain how to run it, and show what you expect to see, and what you see, and then why you think the changes you make should fix it. Then let's discuss it. 

Thanks.

**Comment by dancannon** [comment]
Sure, in the gist I posted (which is based on a test in the `encoding/json` package) I have included a program which attempts to decode some JSON into a struct with an looping data structure and multiple embedded structs. Also included is the output of this program showing the actual and expected data structure.

When using go codec this program fails in two ways, 

1. The program never ends as it gets stuck trying to get the TypeInfo for the `Loop` struct.
2. If the loop is removed the program does not return the expected output as the incorrect fields are "promoted" as specified by the rules in `encoding/json` https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L1093-L1098

I created this PR with a fix for the first issue and to start a discussion about how the second issue might be fixed.

**Comment by ugorji** [comment]
Thanks Dan. Looks good.

I looked at the code again, and I want to make a few more changes to clarify the rules, and align the 
code with them, and to move away from using maps as linear iteration of slices perform better for small number of elements (which is what map may end up doing after all the indirection and heap usage).

I am accepting this PR for the fix now, but it may change soon.

**Comment by ugorji** [comment]
BTW, regarding the second one, I don't want to integrate the json logic for embedded values; it's over-engineered IMO, and should be simpler. Since codec is for multiple formats, we don't take on all the ideosynchracies of encoding/json (or soon encoding/xml). 

I prefer to stop at the spec's definition of embedding, which summarily states that the outer-struct wins if field names are equal. We extend this to encoding names also.

**Comment by ugorji** [comment]
See 1a25ccb806da87b0dff1ba1c0bab1750700dff72 for solution streamlining the handling of embedded values.

With this change, your gist mostly works, except that Embed0a is nil, because it is over-shadowed per typical go's anonymous handling. I really don't like the way encoding/json deviates from regular go's anonymous handling for some edge cases, so don't want to include it for all encodings supported in this library.

**Pull request merged**
