### PR TITLE
mod: justify mod style

### PR DESCRIPTION
**Pull request by hnlq715**
In this way, we can get the right tag like v1.1.3, instead of pseudo-version

A good example would be shown below

https://github.com/stretchr/testify/blob/master/go.mod
https://github.com/andrewstuart/go-robinhood/blob/master/go.mod#L8

go-robinhood imports `github.com/stretchr/testify/assert` and got the right version
```
github.com/stretchr/testify v1.2.2
```

### CODE REVIEW

**Comment by hnlq715** [comment]
@ugorji please consider to merge this PR, thanks

**Comment by ugorji** [comment]
I don't understand why this is necessary, why it works, or what exactly it does. 

What problem did it fix? Why do I need a go.sum that is very clearly incomprehensible to me, the author?

**Comment by ugorji** [comment]
But github.com/Ugorji/go is not the module. The module is .../codec. This
repo might morph to be a multi-module repo.

**Comment by hnlq715** [comment]
yep, we could use codec as submodule of github.com/ugorji/go, which follows the go mod style better :-)

just like github.com/stretchr/testify did

**Comment by ugorji** [comment]
Right. But submodules are so ... intrusive and messes up the git history. I would rather wait a bit and let the bug be fixed, so that subdirectory works just as well.

**Comment by hnlq715** [comment]
this is just the rule declaimed by go mod, I do hope you merge this pull request to avoid pseudo-version, and submodule of go mod works perfectly, it's not the same thing like git submodules.

**Comment by ugorji** [comment]
This PR is not a submodules, I don't understand the changes in go.sum, and I don't know what it's fixing.

I can't merge that.

I will be happy to merge something that I understand and agree with how/what it fixes. Some if that requires some education of me.

**Comment by hnlq715** [comment]
alright, let's talk subdirectory instead of submodules...and the submodule I mentioned is just the same as package's subdirectory.

actually, go.sumgenerated in this PR comes from https://github.com/golang/tools/blob/master/go.sum

as the go modules wiki said, go.sum is used to check the download copies.

> go.sum contains the expected cryptographic checksums of the content of specific module versions.
> 
> If someone clones your repository and downloads your dependencies using the go command, they will receive an error if there is any mismatch between their downloaded copies of your dependencies and the corresponding entries in your go.sum.

Or if you do not accept the go.sum, I can even remove this, because this is not the key point of this PR... instead the go.mod file is

**Comment by hnlq715** [comment]
and this go.sum is auto generated by `go mod tidy`

**Comment by ugorji** [comment]
I don't know what you're fixing. Can you demonstrate a reproducer?

**Comment by ugorji** [comment]
See #279

**Comment by ugorji** [comment]
@hnlq715 can you please try this again with go 1.12 (just released)? Maybe that is why you see a problem, but I don't know what you see, so I cannot reproduce.

**Comment by ugorji** [comment]
Closing this, as I don't even know what it is trying to fix, or if there is a problem here, and OP is now unresponsive.

**Pull request closed without merging**
