### PR TITLE
Run go fmt.

### PR DESCRIPTION
**Pull request by Bren2010**

### CODE REVIEW

**Comment by ugorji** [comment]
Not go managed file.

**Comment by Bren2010** [comment]
All it did was remove trailing whitespace. What's wrong with that?

**Comment by ugorji** [comment]
Sorry - not a fan of "go fmt" PRs, especially those that just remove a few whitespaces from comments.

**Comment by Bren2010** [comment]
I didn't mean to offend you -- it's just that the way I vendor code is constantly fighting with "go fmt" about whether or not some whitespace should be in a file, and I have to fix it manually every time. Surely lots of other people are having this problem, so I thought I'd upstream the fix.

**Pull request closed without merging**
